# Generated by Django 4.2.4 on 2023-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('greenhouse_number', models.IntegerField()),
                ('variety', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('staff_number', models.IntegerField()),
                ('rejected_flowers', models.IntegerField(default=0)),
                ('rejection_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
