# Generated by Django 4.2.4 on 2023-09-18 08:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(default='', max_length=30)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff_number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='greenhouse.user')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(auto_now_add=True)),
                ('greenhouse_number', models.IntegerField()),
                ('variety', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rejected_flowers', models.IntegerField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='greenhouse.user')),
            ],
        ),
    ]
