# Generated by Django 4.2.4 on 2023-09-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_number',
            field=models.IntegerField(null=True),
        ),
    ]
