# Generated by Django 4.2.4 on 2023-09-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-staff_number'], 'permissions': (('can edit', 'To provide edit form'), ('can download reports', 'To provide download access'))},
        ),
        migrations.RemoveField(
            model_name='production',
            name='staff_number',
        ),
        migrations.AddField(
            model_name='production',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='greenhouse.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='rejected_flowers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
