# Generated by Django 4.2.4 on 2023-09-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_alter_production_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
