# Generated by Django 4.2.4 on 2023-09-11 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0004_rename_staff_production_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
