# Generated by Django 4.2.4 on 2023-09-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0008_remove_production_staff_member_production_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Staff Member'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='greenhouse_user',
        ),
    ]
