# Generated by Django 4.2.4 on 2023-09-26 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0009_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
