# Generated by Django 4.2.4 on 2023-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0012_remove_variety_varieties_variety_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='variety',
        ),
        migrations.AddField(
            model_name='production',
            name='varieties',
            field=models.ManyToManyField(to='greenhouse.variety'),
        ),
    ]
