# Generated by Django 4.2.4 on 2023-10-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0015_remove_production_new_varieties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='new_varieties',
            new_name='varieties',
        ),
    ]
