# Generated by Django 4.2.4 on 2023-10-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0019_variety_alter_production_varieties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='varieties',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='greenhouse.variety'),
        ),
    ]
