# Generated by Django 4.2.4 on 2023-10-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0021_alter_production_varieties_delete_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='greenhouse_number',
            field=models.CharField(choices=[('1', 'GH 1'), ('2', 'GH 2'), ('3', 'GH 3'), ('4', 'GH 4'), ('5', 'GH 5'), ('6', 'GH 6'), ('7', 'GH 7'), ('8', 'GH 8'), ('9', 'GH 9'), ('10', 'GH 10'), ('11', 'GH 11'), ('12', 'GH 12'), ('13', 'GH 13'), ('14', 'GH 14'), ('15', 'GH 15'), ('16', 'GH 16'), ('17', 'GH 17'), ('18', 'GH 18'), ('19', 'GH 19'), ('20', 'GH 20'), ('21', 'GH 21'), ('22', 'GH 22'), ('23', 'GH 23'), ('24', 'GH 24'), ('25', 'GH 25'), ('26', 'GH 26'), ('27', 'GH 27'), ('28', 'GH 28'), ('29', 'GH 29'), ('30', 'GH 30'), ('31', 'GH 31'), ('32', 'GH 32'), ('33', 'GH 33'), ('34', 'GH 34'), ('35', 'GH 35'), ('36', 'GH 36'), ('37', 'GH 37'), ('38', 'GH 38'), ('39', 'GH 39'), ('40', 'GH 40'), ('41', 'GH 41'), ('42', 'GH 42'), ('43', 'GH 43'), ('44', 'GH 44'), ('45', 'GH 45'), ('46', 'GH 46'), ('47', 'GH 47'), ('48', 'GH 48'), ('49', 'GH 49'), ('50', 'GH 50'), ('51', 'GH 51'), ('52', 'GH 52'), ('53', 'GH 53'), ('54', 'GH 54'), ('55', 'GH 55'), ('56', 'GH 56'), ('57', 'GH 57'), ('58', 'GH 58'), ('59', 'GH 59'), ('60', 'GH 60'), ('61', 'GH 61'), ('62', 'GH 62')], default='GH 1', max_length=50),
        ),
    ]
