# Generated by Django 4.2.4 on 2023-10-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0022_alter_production_greenhouse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='rejection_reason',
            field=models.CharField(choices=[('BENT STEMS', 'BENT STEMS'), ('GOOSE NECKS', 'GOOSE NECKS'), ('BULL HEADS', 'BULL HEADS'), ('OFF COLOUR', 'OFF COLOUR'), ('WEAK STEMS', 'WEAK STEMS'), ('YELLOWING', 'YELLOWING'), ('APHIDS', 'APHIDS'), ('CATERPILLARS', 'CATERPILLARS'), ('MITES', 'MITES'), ('THRIPS', 'THRIPS'), ('POWDERY MILDEW', 'POWDERY MILDEW'), ('DOWNEY', 'DOWNEY'), ('BOTRYTIS', 'BOTRYTIS'), ('BROKEN STEMS', 'BROKEN STEMS'), ('Bruises & Mechanical damages', 'Bruises & Mechanical damages'), ('CHEMICAL SCORCHES', 'CHEMICAL SCORCHES'), ('CHEMICAL RESIDUE', 'CHEMICAL RESIDUE'), ('MUTATION', 'MUTATION'), ('TOO OPEN', 'TOO OPEN'), ('UNDER SIZE', 'UNDER SIZE'), ('ROTTEN', 'ROTTEN'), ('SMALL HEADS', 'SMALL HEADS')], default='BENT STEMS', max_length=100),
        ),
    ]
