# Generated by Django 4.2.4 on 2023-11-16 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0023_alter_production_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='rejected_flowers',
        ),
        migrations.RemoveField(
            model_name='production',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='production',
            name='total_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='RejectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_date', models.DateField()),
                ('greenhouse_number', models.CharField(choices=[('1', 'GH 1'), ('2', 'GH 2'), ('3', 'GH 3'), ('4', 'GH 4'), ('5', 'GH 5'), ('6', 'GH 6'), ('7', 'GH 7'), ('8', 'GH 8'), ('9', 'GH 9'), ('10', 'GH 10'), ('11', 'GH 11'), ('12', 'GH 12'), ('13', 'GH 13'), ('14', 'GH 14'), ('15', 'GH 15'), ('16', 'GH 16'), ('17', 'GH 17'), ('18', 'GH 18'), ('19', 'GH 19'), ('20', 'GH 20'), ('21', 'GH 21'), ('22', 'GH 22'), ('23', 'GH 23'), ('24', 'GH 24'), ('25', 'GH 25'), ('26', 'GH 26'), ('27', 'GH 27'), ('28', 'GH 28'), ('29', 'GH 29'), ('30', 'GH 30'), ('31', 'GH 31'), ('32', 'GH 32'), ('33', 'GH 33'), ('34', 'GH 34'), ('35', 'GH 35'), ('36', 'GH 36'), ('37', 'GH 37'), ('38', 'GH 38'), ('39', 'GH 39'), ('40', 'GH 40'), ('41', 'GH 41'), ('42', 'GH 42'), ('43', 'GH 43'), ('44', 'GH 44'), ('45', 'GH 45'), ('46', 'GH 46'), ('47', 'GH 47'), ('48', 'GH 48'), ('49', 'GH 49'), ('50', 'GH 50'), ('51', 'GH 51'), ('52', 'GH 52'), ('53', 'GH 53'), ('54', 'GH 54'), ('55', 'GH 55'), ('56', 'GH 56'), ('57', 'GH 57'), ('58', 'GH 58'), ('59', 'GH 59'), ('60', 'GH 60'), ('61', 'GH 61'), ('62', 'GH 62')], default='GH 1', max_length=50)),
                ('varieties', models.CharField(choices=[('Athena', 'Athena'), ('Belle Rose', 'Belle Rose'), ('Confidential', 'Confidential'), ('Espana', 'Espana'), ('Esperance', 'Esperance'), ('Ever Red', 'Ever Red'), ('Fire Expressions', 'Fire Expressions'), ('Fuschiana', 'Fuschiana'), ('Golden Finch', 'Golden Finch'), ('Good times', 'Good times'), ('Jumilia', 'Jumilia'), ('Madam Cerise', 'Madam Cerise'), ('Madam Pink', 'Madam Pink'), ('Madam Red', 'Madam Red'), ('Magic Avalanche+', 'Magic Avalanche+'), ('Mandala', 'Mandala'), ('Miss Mardi', 'Miss Mardi'), ('Moonwalk', 'Moonwalk'), ('New Orleans', 'New Orleans'), ('Novavita', 'Novavita'), ('Opala', 'Opala'), ('Revival', 'Revival'), ('Tacazzi+', 'Tacazzi+'), ('Tara', 'Tara'), ('Wham', 'Wham'), ('Yellowing', 'Yellowing')], default='Athena', max_length=50)),
                ('rejected_number', models.IntegerField(default=0)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rejection_reason', models.CharField(choices=[('BENT STEMS', 'BENT STEMS'), ('GOOSE NECKS', 'GOOSE NECKS'), ('BULL HEADS', 'BULL HEADS'), ('OFF COLOUR', 'OFF COLOUR'), ('WEAK STEMS', 'WEAK STEMS'), ('YELLOWING', 'YELLOWING'), ('APHIDS', 'APHIDS'), ('CATERPILLARS', 'CATERPILLARS'), ('MITES', 'MITES'), ('THRIPS', 'THRIPS'), ('POWDERY MILDEW', 'POWDERY MILDEW'), ('DOWNEY', 'DOWNEY'), ('BOTRYTIS', 'BOTRYTIS'), ('BROKEN STEMS', 'BROKEN STEMS'), ('Bruises & Mechanical damages', 'Bruises & Mechanical damages'), ('CHEMICAL SCORCHES', 'CHEMICAL SCORCHES'), ('CHEMICAL RESIDUE', 'CHEMICAL RESIDUE'), ('MUTATION', 'MUTATION'), ('TOO OPEN', 'TOO OPEN'), ('UNDER SIZE', 'UNDER SIZE'), ('ROTTEN', 'ROTTEN'), ('SMALL HEADS', 'SMALL HEADS')], default='Bent Stems', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
