# Generated by Django 4.2.4 on 2023-11-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0024_remove_production_rejected_flowers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejecteddata',
            name='length',
        ),
    ]
