# Generated by Django 4.2.4 on 2023-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0025_remove_rejecteddata_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(auto_now=True),
        ),
    ]
