# Generated by Django 4.2.4 on 2023-11-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0026_alter_production_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejecteddata',
            name='rejection_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
