# Generated by Django 4.2.4 on 2023-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0027_alter_rejecteddata_rejection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='length',
            field=models.CharField(choices=[('35', '35 cm'), ('40', '40 cm'), ('50', '50 cm'), ('60', '60 cm'), ('70', '70 cm'), ('80', '80 cm'), ('90', '90 cm')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rejecteddata',
            name='rejection_date',
            field=models.DateField(),
        ),
    ]
